try:
    from renderers._version import __version__
except ImportError:
    # Source checkout without a built artifact (e.g. editable install
    # before the first ``uv build`` populates ``_version.py``). Real
    # installs always have it.
    __version__ = "0+unknown"

from renderers.base import (
    ChatTemplateTokenizer,
    Content,
    ContentPart,
    ImagePart,
    MULTIMODAL_MODELS,
    Message,
    MultiModalData,
    MultimodalRenderer,
    OffsetTokenizer,
    ParsedResponse,
    ParsedToolCall,
    PlaceholderRange,
    RenderedConversation,
    RenderedTokens,
    RenderedTrainingSample,
    Renderer,
    TextPart,
    ThinkingPart,
    Tokenizer,
    ToolCall,
    ToolCallFunction,
    ToolCallParseStatus,
    ToolSpec,
    VideoPart,
    attribute_text_segments,
    build_training_sample,
    build_trajectory_step,
    create_renderer,
    extract_message_tool_names,
    is_multimodal,
    reject_assistant_in_extension,
    trim_to_turn_close,
)
from renderers.client import MalformedGenerateResponseError, OverlongPromptError
from renderers.configs import (
    AutoRendererConfig,
    BaseRendererConfig,
    config_from_name,
    DefaultRendererConfig,
    DeepSeekR1RendererConfig,
    DeepSeekV3RendererConfig,
    DeepSeekV4RendererConfig,
    GLM45RendererConfig,
    GLM51RendererConfig,
    GLM5RendererConfig,
    Gemma4RendererConfig,
    GptOssRendererConfig,
    Hy3RendererConfig,
    InklingRendererConfig,
    KimiK25RendererConfig,
    KimiK2RendererConfig,
    LagunaM1RendererConfig,
    LagunaS21RendererConfig,
    LagunaXS2RendererConfig,
    LagunaXS21RendererConfig,
    Llama3RendererConfig,
    MiniMaxM2RendererConfig,
    Nemotron35RendererConfig,
    Nemotron3RendererConfig,
    Nemotron3UltraRendererConfig,
    PrimeQwen3RendererConfig,
    Qwen35RendererConfig,
    Qwen36RendererConfig,
    Qwen38RendererConfig,
    Qwen3RendererConfig,
    Qwen3VLRendererConfig,
    RendererConfig,
)
from renderers.token_arrays import (
    MASK_DTYPE,
    MESSAGE_INDICES_DTYPE,
    OFFSETS_DTYPE,
    TOKEN_IDS_DTYPE,
    FixedWidthArrayBuilder,
    FixedWidthRangeBuilder,
    RenderedTokenBuilder,
    TextSegmentBuilder,
    encode_token_ids,
    finish_range_builders,
    merge_range_maps,
)

# Concrete renderer classes are lazy-loaded so that consumers needing only the
# config layer (``RendererConfig`` discriminated union) don't import every
# renderer module. Renderer tokenizer annotations use the local ``Tokenizer``
# protocols, so resolving a text renderer remains safe when the optional
# ``transformers`` dependency is absent. ``__getattr__`` (PEP 562) resolves the
# names on first attribute access, while ``renderers.base._populate_registry``
# handles lazy registration for ``create_renderer``.
_LAZY_RENDERERS: dict[str, str] = {
    "DeepSeekR1Renderer": "renderers.deepseek_r1",
    "DeepSeekV3Renderer": "renderers.deepseek_v3",
    "DeepSeekV4Renderer": "renderers.deepseek_v4",
    "DefaultRenderer": "renderers.default",
    "GLM45Renderer": "renderers.glm45",
    "GLM51Renderer": "renderers.glm5",
    "GLM5Renderer": "renderers.glm5",
    "GptOssRenderer": "renderers.gpt_oss",
    "Gemma4Renderer": "renderers.gemma4",
    "Hy3Renderer": "renderers.hy3",
    "InklingRenderer": "renderers.inkling",
    "KimiK25Renderer": "renderers.kimi_k25",
    "KimiK2Renderer": "renderers.kimi_k2",
    "LagunaM1Renderer": "renderers.laguna_xs2",
    "LagunaS21Renderer": "renderers.laguna_s21",
    "LagunaXS21Renderer": "renderers.laguna_xs2",
    "LagunaXS2Renderer": "renderers.laguna_xs2",
    "Llama3Renderer": "renderers.llama_3",
    "MiniMaxM2Renderer": "renderers.minimax_m2",
    "Nemotron35Renderer": "renderers.nemotron3",
    "Nemotron3Renderer": "renderers.nemotron3",
    "Nemotron3UltraRenderer": "renderers.nemotron3",
    "PrimeQwen3Renderer": "renderers.prime_qwen3",
    "Qwen35Renderer": "renderers.qwen35",
    "Qwen36Renderer": "renderers.qwen36",
    "Qwen38Renderer": "renderers.qwen38",
    "Qwen3Renderer": "renderers.qwen3",
    "Qwen3VLRenderer": "renderers.qwen3_vl",
}


def __getattr__(name: str):
    if name in _LAZY_RENDERERS:
        import importlib

        module = importlib.import_module(_LAZY_RENDERERS[name])
        value = getattr(module, name)
        globals()[name] = value  # cache for subsequent lookups
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted(set(globals().keys()) | set(_LAZY_RENDERERS))


__all__ = [
    "AutoRendererConfig",
    "BaseRendererConfig",
    "ChatTemplateTokenizer",
    "Content",
    "ContentPart",
    "DeepSeekR1Renderer",
    "DeepSeekR1RendererConfig",
    "DeepSeekV3Renderer",
    "DeepSeekV3RendererConfig",
    "DeepSeekV4Renderer",
    "DeepSeekV4RendererConfig",
    "DefaultRenderer",
    "DefaultRendererConfig",
    "GLM45Renderer",
    "GLM45RendererConfig",
    "GLM51Renderer",
    "GLM51RendererConfig",
    "GLM5Renderer",
    "GLM5RendererConfig",
    "FixedWidthRangeBuilder",
    "FixedWidthArrayBuilder",
    "Gemma4Renderer",
    "Gemma4RendererConfig",
    "GptOssRenderer",
    "GptOssRendererConfig",
    "Hy3Renderer",
    "Hy3RendererConfig",
    "ImagePart",
    "InklingRenderer",
    "InklingRendererConfig",
    "KimiK25Renderer",
    "KimiK25RendererConfig",
    "KimiK2Renderer",
    "KimiK2RendererConfig",
    "LagunaM1Renderer",
    "LagunaM1RendererConfig",
    "LagunaS21Renderer",
    "LagunaS21RendererConfig",
    "LagunaXS2Renderer",
    "LagunaXS2RendererConfig",
    "LagunaXS21Renderer",
    "LagunaXS21RendererConfig",
    "Llama3Renderer",
    "Llama3RendererConfig",
    "MULTIMODAL_MODELS",
    "MASK_DTYPE",
    "MESSAGE_INDICES_DTYPE",
    "MalformedGenerateResponseError",
    "Message",
    "MiniMaxM2Renderer",
    "MiniMaxM2RendererConfig",
    "MultiModalData",
    "MultimodalRenderer",
    "Nemotron35Renderer",
    "Nemotron35RendererConfig",
    "Nemotron3Renderer",
    "Nemotron3RendererConfig",
    "Nemotron3UltraRenderer",
    "Nemotron3UltraRendererConfig",
    "OffsetTokenizer",
    "OFFSETS_DTYPE",
    "OverlongPromptError",
    "ParsedResponse",
    "ParsedToolCall",
    "PlaceholderRange",
    "PrimeQwen3Renderer",
    "PrimeQwen3RendererConfig",
    "Qwen35Renderer",
    "Qwen35RendererConfig",
    "Qwen36Renderer",
    "Qwen36RendererConfig",
    "Qwen38Renderer",
    "Qwen38RendererConfig",
    "Qwen3Renderer",
    "Qwen3RendererConfig",
    "Qwen3VLRenderer",
    "Qwen3VLRendererConfig",
    "RenderedConversation",
    "RenderedTokens",
    "RenderedTokenBuilder",
    "RenderedTrainingSample",
    "Renderer",
    "RendererConfig",
    "TextPart",
    "TextSegmentBuilder",
    "ThinkingPart",
    "Tokenizer",
    "ToolCall",
    "ToolCallFunction",
    "ToolCallParseStatus",
    "ToolSpec",
    "TOKEN_IDS_DTYPE",
    "VideoPart",
    "__version__",
    "attribute_text_segments",
    "build_training_sample",
    "build_trajectory_step",
    "config_from_name",
    "create_renderer",
    "extract_message_tool_names",
    "encode_token_ids",
    "finish_range_builders",
    "is_multimodal",
    "merge_range_maps",
    "reject_assistant_in_extension",
    "trim_to_turn_close",
]
